# -*- mode: ruby -*-
# vi: set ft=ruby :

# See README.md for details

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos65-base"

  config.vm.define "puppetmaster" do |puppetmaster|
  
    puppetmaster.vm.hostname = "puppetmaster"
  
    puppetmaster.vm.network "private_network", ip: "192.168.1.104"
  
  end
  
end
